### ISSUE TITLE
Shared link loses the visualization

### ISSUE THREAD

**Issue by tracycarley** [jupyterlab-contrib/jupyterlab-link-share#20]
## Description

Shared Link is visible by team mates but the visualization got lost. Plots Matlab graphs are not visible by others.

## Reproduce

Run a notebook that generates plotly/matlab results with some sort of visualization. Let it render. Go to Share, send the link to other collaborators.

## Expected behavior

Plots are also visible by other collaborators 

## Context

```
jupyter --version
Selected Jupyter core packages...
IPython          : 7.29.0
ipykernel        : 6.5.0
ipywidgets       : 7.6.5
jupyter_client   : 7.0.6
jupyter_core     : 4.9.1
jupyter_server   : 1.11.2
jupyterlab       : 3.2.3
nbclient         : 0.5.8
nbconvert        : 6.3.0
nbformat         : 5.1.3
notebook         : 6.4.6
qtconsole        : not installed
traitlets        : 5.1.1
```

```
jupyter labextension list
JupyterLab v3.2.3
/usr/local/share/jupyter/labextensions
        jupyter-matplotlib v0.10.2 enabled OK
        jupyterlab-link-share v0.2.1 enabled OK (python, jupyterlab-link-share)
        jupyterlab_templates v0.3.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

Other labextensions (built into JupyterLab)
   app dir: /usr/local/share/jupyter/lab
        jupyterlab-plotly v4.14.3 enabled OK
        plotlywidget v4.14.3 enabled OK
        ```

**Comment by hbcarlos** [comment]
Hi @tracycarley, thanks for opening this issue.
The issue you describe here looks similar to https://github.com/jupyterlab/jupyterlab/issues/11435 in the JupyterLab repo.
There is already a [PR](https://github.com/jupyterlab/jupyterlab/pull/11494) open to solve it.

**Comment by jtpio** [comment]
Thanks @tracycarley and @hbcarlos.

Closing since this doesn't seem to be related to the link share extension, which is limited to creating a link and does not interact with the outputs.

We can continue the discussion in https://github.com/jupyterlab/jupyterlab/issues/11435 and https://github.com/jupyterlab/jupyterlab/pull/11494.
