### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-link-share#3]
For now `jupyterlab-link-share` is only published to PyPI and conda-forge for JupyterLab 3.0.

However it could also be published to `npm` if users prefer to install source extensions.

**Comment by fcollonval** [comment]
As you mentioned, I'm not sure this should be required for new extension as publication through pip/conda will be easier. So I'm fine if you want to close this one.

**Comment by jtpio** [comment]
Fixed by #16 

The npm package was automatically published by the releaser: https://www.npmjs.com/package/jupyterlab-link-share
